// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Superset Ingress
---
*/
package cmds

import (
	"context"

	"github.com/365admin/nats-infrastructure/execution"
	"github.com/365admin/nats-infrastructure/utils"
)

func ProvisionSupersetIngressPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "nats-infrastructure", "60-provision", "20-nats-ingress.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
