// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: 10-kill.ps1
---
*/
package cmds

import (
	"context"

	"github.com/365admin/nats-infrastructure/execution"
	"github.com/365admin/nats-infrastructure/utils"
)

func ServerKillPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "nats-infrastructure", "10-server", "10-kill.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
