// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Start
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/365admin/nats-infrastructure/execution"
)

func CustomStartPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "nats-infrastructure", "run", "start.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Start")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Custom Caddy")
	return u
}
